# Generated by Django 5.1.4 on 2025-02-08 20:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 8, 20, 31, 1, 405501, tzinfo=datetime.timezone.utc)),
        ),
    ]
