# Generated by Django 5.1.4 on 2025-01-10 21:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 7, 21, 32, 1, 681547, tzinfo=datetime.timezone.utc)),
        ),
    ]
