# Generated by Django 5.1.4 on 2025-02-09 14:29

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_alter_competition_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='achieved_at',
        ),
        migrations.AddField(
            model_name='goal',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='competition',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 9, 14, 29, 34, 525045, tzinfo=datetime.timezone.utc)),
        ),
    ]
