# Generated by Django 5.1.4 on 2025-01-10 22:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0003_alter_competition_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 7, 22, 3, 33, 25538, tzinfo=datetime.timezone.utc)),
        ),
    ]
