# Generated by Django 5.1.4 on 2025-01-19 13:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0004_alter_competition_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='competition',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='competition',
        ),
        migrations.AddField(
            model_name='competition',
            name='categories',
            field=models.ManyToManyField(related_name='competitions', to='competitions.category'),
        ),
        migrations.AddField(
            model_name='competition',
            name='participants',
            field=models.ManyToManyField(related_name='competitions', to='competitions.participant'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 16, 13, 40, 32, 434392, tzinfo=datetime.timezone.utc)),
        ),
    ]
