# Generated by Django 5.1.4 on 2025-01-19 15:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0007_alter_competition_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 16, 15, 4, 42, 85238, tzinfo=datetime.timezone.utc)),
        ),
    ]
