# Generated by Django 5.1.4 on 2025-01-20 03:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0013_alter_competition_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 17, 3, 38, 52, 957482, tzinfo=datetime.timezone.utc)),
        ),
    ]
