# Generated by Django 5.1.4 on 2025-01-22 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0005_alter_competition_end_date'),
        ('competitions', '0014_alter_competition_end_date'),
    ]

    operations = [
    ]
