# Generated by Django 5.1.4 on 2025-01-23 17:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0015_merge_20250122_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='competition',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 20, 17, 20, 1, 304441, tzinfo=datetime.timezone.utc)),
        ),
    ]
