# Generated by Django 5.1.4 on 2025-01-22 18:33

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0016_alter_competition_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='competitions_owned', to='competitions.participant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='competition',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 19, 18, 33, 34, 805516, tzinfo=datetime.timezone.utc)),
        ),
    ]
