# Generated by Django 5.1.4 on 2025-01-23 18:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0016_category_public_alter_competition_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 20, 18, 55, 58, 488964, tzinfo=datetime.timezone.utc)),
        ),
    ]
