# Generated by Django 5.1.4 on 2025-01-22 18:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0017_competition_owner_alter_competition_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 19, 18, 34, 9, 736296, tzinfo=datetime.timezone.utc)),
        ),
    ]
