# Generated by Django 5.1.4 on 2025-01-23 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0017_alter_competition_end_date'),
        ('competitions', '0018_alter_competition_end_date'),
    ]

    operations = [
    ]
