# Generated by Django 5.1.4 on 2025-01-24 15:17

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0019_merge_20250123_1938'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='participants',
        ),
        migrations.AddField(
            model_name='competition',
            name='admins',
            field=models.ManyToManyField(related_name='admin_competitions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='participant',
            name='competition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='competitions.competition'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 21, 15, 17, 9, 824940, tzinfo=datetime.timezone.utc)),
        ),
    ]
